/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { TaskCreateNestedManyWithoutProjectsInput } from "./TaskCreateNestedManyWithoutProjectsInput";
import { ChatCreateNestedManyWithoutProjectsInput } from "./ChatCreateNestedManyWithoutProjectsInput";

@InputType()
class ProjectCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startDate?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endDate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  owner?: string | null;

  @ApiProperty({
    required: false,
    type: () => TaskCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => TaskCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => TaskCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  tasks?: TaskCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: () => ChatCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => ChatCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => ChatCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  chats?: ChatCreateNestedManyWithoutProjectsInput;
}

export { ProjectCreateInput as ProjectCreateInput };
